### ISSUE TITLE
Cache/NetworkDispatcher leaking finished requests

### ISSUE THREAD

**Issue by Dayanand515** [google/volley#114] opened 2017-10-31 06:48 UTC
Hi Team,
com.android.volley.Request#finish is not clearing mErrorListener, not its calling onFinish as is the case with https://github.com/mcxiaoke/android-volley/blob/master/src/main/java/com/android/volley/Request.java finish.
due to which error listener is not getting cleared and memory leak is there.

**Comment by Dayanand515** [comment] 2017-10-31 12:21
Please refer https://github.com/mcxiaoke/android-volley/commit/c111d14699a2235ea5d3af51b40bcf67ba310bf8 , onFinish() should be there so that any class extending Request<T> can clear api listeners.

**Comment by jpd236** [comment] 2017-10-31 17:32
At a glance, I can't understand why this should be necessary.

After Request#finish, the Request object goes out of scope - nothing inside Volley's internals should be holding onto it. That means it should be eligible for GC, as should all of its children, including any listeners.

Do you have more information about the leak you are seeing? In particular, do you have a sample app that reproduces it? Are you using LeakCanary and can provide the leak information? What device and Android version are you using to test with, and does it reproduce on other versions?

**Comment by Dayanand515** [comment] 2017-11-01 06:50
Hi Team,

Since on error reqeust is removed from current requests, but still NetworkDispatcher is keeping reference of api listener.
My api listener class :-
public abstract class ApiListeners<T> implements Listener<T>, ErrorListener {

    public void onRequestStarted(ApiRequest<T> req) {

    }

    /**
     * Called on volley background thread
     * @param request
     * @param resString
     * @param response
     */
    public void onDataParsed(ApiRequest<T> request, String resString, T response) {

    }

    public void onResponse(ApiRequest<T> request,  T response) {
        onResponse(response);
    }
}

Volley logs :-



MarkerLog.finish: (427  ms) [ ] {{api_url} 0xab1872ba NORMAL 15
11-01 11:49:00.608 31454-31454/{{package}} D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
11-01 11:49:00.610 31454-31454/{{package}} D/Volley: [1] MarkerLog.finish: (+0   ) [945] cache-queue-take
11-01 11:49:00.610 31454-31454/{{package}} D/Volley: [1] MarkerLog.finish: (+0   ) [945] cache-miss
11-01 11:49:00.610 31454-31454/{{package}} D/Volley: [1] MarkerLog.finish: (+1   ) [947] network-queue-take
11-01 11:49:00.611 31454-31454/{{package}} D/Volley: [1] MarkerLog.finish: (+188 ) [947] post-error
11-01 11:49:00.611 31454-31454/{{package}} D/Volley: [1] MarkerLog.finish: (+238 ) [ 1] done

Leak canary logs :-


In {{package}}:4.4.10:100.
* {{package}}.activity.FoodMenuActivity has leaked:
* GC ROOT com.android.volley.NetworkDispatcher.<Java Local>
* references {{package}}.network.ApiRequest.mListener
* references {{package}}.activity.FoodMenuActivity$1.this$0 (anonymous subclass of {{package}}.network.ApiListeners)
* leaks {{package}}.activity.FoodMenuActivity instance

* Retaining: 14 KB.
* Reference Key: 1c56ddde-1403-4a5b-95c3-4cba2faa789f
* Device: Google google Android SDK built for x86 sdk_google_phone_x86
* Android Version: 7.0 API: 24 LeakCanary: 1.5.4 74837f0
* Durations: watch=5011ms, gc=120ms, heap dump=10075ms, analysis=27631ms

* Details:
* Instance of com.android.volley.NetworkDispatcher
|   static $classOverhead = byte[440]@316635137 (0x12df7801)
|   mCache = com.android.volley.toolbox.DiskBasedCache@316881664 (0x12e33b00)
|   mDelivery = com.android.volley.ExecutorDelivery@316549184 (0x12de2840)
|   mNetwork = com.android.volley.toolbox.BasicNetwork@316826120 (0x12e26208)
|   mQueue = java.util.concurrent.PriorityBlockingQueue@316617600 (0x12df3380)
|   mQuit = false
|   blocker = null
|   blockerLock = java.lang.Object@314580624 (0x12c01e90)
|   contextClassLoader = dalvik.system.PathClassLoader@315558160 (0x12cf0910)
|   daemon = false
|   eetop = 0
|   group = java.lang.ThreadGroup@1864813784 (0x6f26ccd8)
|   inheritableThreadLocals = null
|   inheritedAccessControlContext = java.security.AccessControlContext@314580616 (0x12c01e88)
|   lock = java.lang.Object@314580632 (0x12c01e98)
|   name = java.lang.String@316617760 (0x12df3420)
|   nativeParkEventPointer = 0
|   nativePeer = 2576056832
|   parkBlocker = java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@316828736 (0x12e26c40)
|   parkState = 3
|   priority = 5
|   single_step = false
|   stackSize = 0
|   started = true
|   stillborn = false
|   target = null
|   threadLocalRandomProbe = 0
|   threadLocalRandomSecondarySeed = 0
|   threadLocalRandomSeed = 0
|   threadLocals = java.lang.ThreadLocal$ThreadLocalMap@318730352 (0x12ff7070)
|   threadQ = null
|   threadStatus = 0
|   tid = 947
|   uncaughtExceptionHandler = null
|   shadow$_klass_ = com.android.volley.NetworkDispatcher
|   shadow$_monitor_ = 0
* Instance of {{package}}.network.ApiRequest
|   static $change = null
|   static NETWORK_TIME_MILLIS = java.lang.String@315488008 (0x12cdf708)
|   static GSON = com.google.gson.Gson@315725760 (0x12d197c0)
|   static PROTOCOL_CONTENT_TYPE = java.lang.String@315688368 (0x12d105b0)
|   static $classOverhead = byte[520]@316632065 (0x12df6c01)
|   static PROTOCOL_CHARSET = java.lang.String@1866504416 (0x6f4098e0)
|   static serialVersionUID = -3427260480414714509
|   clazz = {{package}}.api.model.FoodMenuResponse
|   data = android.os.Bundle@318589416 (0x12fd49e8)
|   formData = null
|   headers = android.support.v4.util.ArrayMap@318588720 (0x12fd4730)
|   mListener = {{package}}.activity.FoodMenuActivity$1@315678688 (0x12d0dfe0)
|   mLock = java.lang.Object@315470416 (0x12cdb250)
|   mRequestBody = null
|   mCacheEntry = null
|   mCanceled = false
|   mDefaultTrafficStatsTag = -1424461126
|   mErrorListener = {{package}}.activity.FoodMenuActivity$1@315678688 (0x12d0dfe0)
|   mEventLog = com.android.volley.VolleyLog$MarkerLog@316690384 (0x12e04fd0)
|   mLock = java.lang.Object@315470408 (0x12cdb248)
|   mMethod = 0
|   mRequestCompleteListener = com.android.volley.CacheDispatcher$WaitingRequestManager@316549312 (0x12de28c0)
|   mRequestQueue = com.android.volley.RequestQueue@315726624 (0x12d19b20)
|   mResponseDelivered = false
|   mRetryPolicy = com.android.volley.DefaultRetryPolicy@318589488 (0x12fd4a30)
|   mSequence = java.lang.Integer@1865175408 (0x6f2c5170)
|   mShouldCache = true
|   mShouldRetryServerErrors = false
|   mTag = java.lang.String@317077552 (0x12e63830)
|   mUrl = java.lang.String@319686304 (0x130e06a0)
|   shadow$_klass_ = {{package}}.network.ApiRequest
|   shadow$_monitor_ = -2064561402
* Instance of {{package}}.activity.FoodMenuActivity$1
|   static $change = null
|   static serialVersionUID = 7501698172319344425
|   static $classOverhead = byte[344]@316110497 (0x12d776a1)
|   this$0 = {{package}}.activity.FoodMenuActivity@322841792 (0x133e2cc0)
|   shadow$_klass_ = {{package}}.activity.FoodMenuActivity$1
|   shadow$_monitor_ = 0
* Instance of {{package}}.activity.FoodMenuActivity
|   static $change = null
|   static TAG = java.lang.String@317077552 (0x12e63830)
|   static $classOverhead = byte[2480]@322756609 (0x133ce001)
|   static serialVersionUID = -5751139761726663462
|   foodItemsAvailable = true
|   mBooking = {{package}}.api.model.Booking@323096864 (0x13421120)
|   mCurrentTimeSlot = null
|   mFirstTimeSlot = null
|   mFoodCategoriesPagerAdapter = null
|   mFoodMenuResponseListeners = {{package}}.activity.FoodMenuActivity$1@315678688 (0x12d0dfe0)
|   mItemRemovalAlertDialog = null
|   mLastTimeSlot = null
|   mTimeSlots = null
|   mViewPager = null
|   orderNotPossibleView = null
|   otherComplimentaryItemsSeen = false
|   selectedTimeRangeContainer = null
|   selectedTimeRangeTv = null
|   tabLayout = null
|   timeSlotCandidate = null
|   isComplimentaryFoodMenu = false
|   isDeliveryLater = false
|   mBookingId = 5650880
|   mCurrencySymbol = java.lang.String@318587568 (0x12fd42b0)
|   mFoodCategoryList = null
|   mFreeItemsCount = null
|   mOrderActionView = null
|   mOrderPriceView = null
|   mRoomNumber = java.lang.String@318587472 (0x12fd4250)
|   mSelectedMenuItems = null
|   mealType = java.lang.String@317773920 (0x12f0d860)
|   compositeDisposable = {{package}}.base.CompositeDisposable@315677984 (0x12d0dd20)
|   errorSnackbar = null
|   mActivity = {{package}}.activity.FoodMenuActivity@322841792 (0x133e2cc0)
|   mContext = {{package}}.activity.FoodMenuActivity@322841792 (0x133e2cc0)
|   mCoupleFilterToast = null
|   mLoadingDialog = null
|   mPopUpToShow = null
|   mPopupState = 0
|   mProgressDialog = null
|   mShakeDetector = null
|   mToolbar = android.support.v7.widget.Toolbar@320848896 (0x131fc400)
|   mToolbar = null
|   statusBarHeight = 63
|   mDelegate = android.support.v7.app.AppCompatDelegateImplN@315120080 (0x12c859d0)
|   mEatKeyUpEvent = false
|   mResources = null
|   mThemeId = 2131755272
|   mCreated = true
|   mFragments = android.support.v4.app.FragmentController@315677952 (0x12d0dd00)
|   mHandler = android.support.v4.app.FragmentActivity$1@315517408 (0x12ce69e0)
|   mNextCandidateRequestIndex = 0
|   mOptionsMenuInvalidated = false
|   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@317618568 (0x12ee7988)
|   mReallyStopped = true
|   mRequestedPermissionsFromFragment = false
|   mResumed = false
|   mRetaining = false
|   mStopped = true
|   mStartedActivityFromFragment = false
|   mStartedIntentSenderFromFragment = false
|   mExtraDataMap = android.support.v4.util.SimpleArrayMap@317310192 (0x12e9c4f0)
|   mActionBar = null
|   mActionModeTypeStarting = 0
|   mActivityInfo = android.content.pm.ActivityInfo@317953504 (0x12f395e0)
|   mActivityTransitionState = android.app.ActivityTransitionState@315356992 (0x12cbf740)
|   mApplication = {{package}}.AppController@315595600 (0x12cf9b50)
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mComponent = android.content.ComponentName@315654224 (0x12d08050)
|   mConfigChangeFlags = 0
|   mCurrentConfig = android.content.res.Configuration@315335840 (0x12cba4a0)
|   mDecor = null
|   mDefaultKeyMode = 0
|   mDefaultKeySsb = null
|   mDestroyed = true
|   mDoReportFullyDrawn = false
|   mEatKeyUpEvent = false
|   mEmbeddedID = null
|   mEnableDefaultActionBarUp = false
|   mEnterTransitionListener = android.app.SharedElementCallback$1@1871514504 (0x6f8d0b88)
|   mExitTransitionListener = android.app.SharedElementCallback$1@1871514504 (0x6f8d0b88)
|   mFinished = true
|   mFragments = android.app.FragmentController@315677664 (0x12d0dbe0)
|   mHandler = android.os.Handler@315517344 (0x12ce69a0)
|   mHasCurrentPermissionsRequest = false
|   mIdent = 4605317
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@315677840 (0x12d0dc90)
|   mInstrumentation = android.app.Instrumentation@315673616 (0x12d0cc10)
|   mIntent = android.content.Intent@314921192 (0x12c550e8)
|   mLastNonConfigurationInstances = null
|   mMainThread = android.app.ActivityThread@315572480 (0x12cf4100)
|   mManagedCursors = java.util.ArrayList@317309976 (0x12e9c418)
|   mManagedDialogs = null
|   mMenuInflater = null
|   mParent = null
|   mReferrer = java.lang.String@315956144 (0x12d51bb0)
|   mResultCode = 0
|   mResultData = null
|   mResumed = false
|   mSearchEvent = null
|   mSearchManager = null
|   mStartedActivity = false
|   mStopped = true
|   mTaskDescription = android.app.ActivityManager$TaskDescription@315517376 (0x12ce69c0)
|   mTemporaryPause = false
|   mTitle = java.lang.String@315368112 (0x12cc22b0)
|   mTitleColor = 0
|   mTitleReady = true
|   mToken = android.os.BinderProxy@315879648 (0x12d3f0e0)
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread@1944190976 (0x73e20000)
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.PhoneWindow@318277568 (0x12f887c0)
|   mWindowAdded = true
|   mWindowManager = android.view.WindowManagerImpl@317482368 (0x12ec6580)
|   mInflater = com.android.internal.policy.PhoneLayoutInflater@316752464 (0x12e14250)
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources@317077712 (0x12e638d0)
|   mTheme = android.content.res.Resources$Theme@315678048 (0x12d0dd60)
|   mThemeResource = 2131755272
|   mBase = android.app.ContextImpl@316048640 (0x12d68500)
|   shadow$_klass_ = {{package}}.activity.FoodMenuActivity
|   shadow$_monitor_ = 1212025866
* Excluded Refs:
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.textservice.SpellCheckerSession$1.this$0
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by Dayanand515** [comment] 2017-11-01 11:08
Hi Team,
I have created a sample app for the same at 
https://github.com/Dayanand515/TestVolley

1. Please install app, and click on "Click Me" text,
2.  After some time when on another screen "Api Error Occurred" text is shown , press back,
3. wait for sometime.

Leak is shown by leak canary.

In testvolley.dn.java.testvolley:1.0:1.
* testvolley.dn.java.testvolley.ApiActivity has leaked:
* GC ROOT com.android.volley.CacheDispatcher.<Java Local>
* references testvolley.dn.java.testvolley.ApiRequest.mListener
* references testvolley.dn.java.testvolley.ApiActivity$1.this$0 (anonymous subclass of testvolley.dn.java.testvolley.ApiListeners)
* leaks testvolley.dn.java.testvolley.ApiActivity instance

* Retaining: 44 KB.
* Reference Key: 3dff8f1a-d489-4efa-ab82-0a70fdad72d5
* Device: Google google Android SDK built for x86 sdk_google_phone_x86
* Android Version: 7.0 API: 24 LeakCanary: 1.5.4 74837f0
* Durations: watch=5010ms, gc=113ms, heap dump=8480ms, analysis=9607ms

* Details:
* Instance of com.android.volley.CacheDispatcher
|   static $classOverhead = byte[441]@717252609 (0x2ac06801)
|   static DEBUG = true
|   mCache = com.android.volley.toolbox.DiskBasedCache@717964288 (0x2acb4400)
|   mCacheQueue = java.util.concurrent.PriorityBlockingQueue@717226360 (0x2ac00178)
|   mDelivery = com.android.volley.ExecutorDelivery@717972272 (0x2acb6330)
|   mNetworkQueue = java.util.concurrent.PriorityBlockingQueue@717226400 (0x2ac001a0)
|   mQuit = false
|   mWaitingRequestManager = com.android.volley.CacheDispatcher$WaitingRequestManager@718148064 (0x2ace11e0)
|   blocker = null
|   blockerLock = java.lang.Object@717259704 (0x2ac083b8)
|   contextClassLoader = dalvik.system.PathClassLoader@717328928 (0x2ac19220)
|   daemon = false
|   eetop = 0
|   group = java.lang.ThreadGroup@1864813784 (0x6f26ccd8)
|   inheritableThreadLocals = null
|   inheritedAccessControlContext = java.security.AccessControlContext@717259712 (0x2ac083c0)
|   lock = java.lang.Object@717258840 (0x2ac08058)
|   name = java.lang.String@718138816 (0x2acdedc0)
|   nativeParkEventPointer = 0
|   nativePeer = 2653233408
|   parkBlocker = java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@717238432 (0x2ac030a0)
|   parkState = 3
|   priority = 5
|   single_step = false
|   stackSize = 0
|   started = true
|   stillborn = false
|   target = null
|   threadLocalRandomProbe = 0
|   threadLocalRandomSecondarySeed = 0
|   threadLocalRandomSeed = 0
|   threadLocals = java.lang.ThreadLocal$ThreadLocalMap@718152968 (0x2ace2508)
|   threadQ = null
|   threadStatus = 0
|   tid = 1171
|   uncaughtExceptionHandler = null
|   shadow$_klass_ = com.android.volley.CacheDispatcher
|   shadow$_monitor_ = 0
* Instance of testvolley.dn.java.testvolley.ApiRequest
|   static $classOverhead = byte[512]@717876225 (0x2ac9ec01)
|   static NETWORK_TIME_MILLIS = java.lang.String@717285800 (0x2ac0e9a8)
|   static PROTOCOL_CHARSET = java.lang.String@1866504416 (0x6f4098e0)
|   static $change = null
|   static GSON = com.google.gson.Gson@717330944 (0x2ac19a00)
|   static serialVersionUID = -7557160610015252903
|   static PROTOCOL_CONTENT_TYPE = java.lang.String@717992112 (0x2acbb0b0)
|   clazz = testvolley.dn.java.testvolley.User
|   data = android.os.Bundle@718328592 (0x2ad0d310)
|   formData = null
|   headers = null
|   mListener = testvolley.dn.java.testvolley.ApiActivity$1@718193072 (0x2acec1b0)
|   mLock = java.lang.Object@718282872 (0x2ad02078)
|   mRequestBody = null
|   mCacheEntry = null
|   mCanceled = false
|   mDefaultTrafficStatsTag = -1504897081
|   mErrorListener = testvolley.dn.java.testvolley.ApiActivity$1@718193072 (0x2acec1b0)
|   mEventLog = com.android.volley.VolleyLog$MarkerLog@718193824 (0x2acec4a0)
|   mLock = java.lang.Object@718282864 (0x2ad02070)
|   mMethod = 0
|   mRequestCompleteListener = com.android.volley.CacheDispatcher$WaitingRequestManager@718148064 (0x2ace11e0)
|   mRequestQueue = com.android.volley.RequestQueue@717330848 (0x2ac199a0)
|   mResponseDelivered = false
|   mRetryPolicy = com.android.volley.DefaultRetryPolicy@718328616 (0x2ad0d328)
|   mSequence = java.lang.Integer@1865173152 (0x6f2c48a0)
|   mShouldCache = true
|   mShouldRetryServerErrors = false
|   mTag = java.lang.String@717270032 (0x2ac0ac10)
|   mUrl = java.lang.String@717279328 (0x2ac0d060)
|   shadow$_klass_ = testvolley.dn.java.testvolley.ApiRequest
|   shadow$_monitor_ = -1928631308
* Instance of testvolley.dn.java.testvolley.ApiActivity$1
|   static $classOverhead = byte[344]@717868097 (0x2ac9cc41)
|   static serialVersionUID = 2031432410671757167
|   static $change = null
|   this$0 = testvolley.dn.java.testvolley.ApiActivity@717956704 (0x2acb2660)
|   shadow$_klass_ = testvolley.dn.java.testvolley.ApiActivity$1
|   shadow$_monitor_ = 0
* Instance of testvolley.dn.java.testvolley.ApiActivity
|   static $classOverhead = byte[2064]@717987841 (0x2acba001)
|   static url = java.lang.String@717279328 (0x2ac0d060)
|   static $change = null
|   static serialVersionUID = 705608175010244991
|   userApiListeners = testvolley.dn.java.testvolley.ApiActivity$1@718193072 (0x2acec1b0)
|   mActionBar = null
|   mActionModeTypeStarting = 0
|   mActivityInfo = android.content.pm.ActivityInfo@717782896 (0x2ac87f70)
|   mActivityTransitionState = android.app.ActivityTransitionState@718225584 (0x2acf40b0)
|   mApplication = testvolley.dn.java.testvolley.MyApplication@717967168 (0x2acb4f40)
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mComponent = android.content.ComponentName@718237776 (0x2acf7050)
|   mConfigChangeFlags = 0
|   mCurrentConfig = android.content.res.Configuration@718287200 (0x2ad03160)
|   mDecor = null
|   mDefaultKeyMode = 0
|   mDefaultKeySsb = null
|   mDestroyed = true
|   mDoReportFullyDrawn = false
|   mEatKeyUpEvent = false
|   mEmbeddedID = null
|   mEnableDefaultActionBarUp = false
|   mEnterTransitionListener = android.app.SharedElementCallback$1@1871514504 (0x6f8d0b88)
|   mExitTransitionListener = android.app.SharedElementCallback$1@1871514504 (0x6f8d0b88)
|   mFinished = true
|   mFragments = android.app.FragmentController@718193040 (0x2acec190)
|   mHandler = android.os.Handler@718209312 (0x2acf0120)
|   mHasCurrentPermissionsRequest = false
|   mIdent = 19746635
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@718193056 (0x2acec1a0)
|   mInstrumentation = android.app.Instrumentation@717314872 (0x2ac15b38)
|   mIntent = android.content.Intent@718229624 (0x2acf5078)
|   mLastNonConfigurationInstances = null
|   mMainThread = android.app.ActivityThread@717242624 (0x2ac04100)
|   mManagedCursors = java.util.ArrayList@718197040 (0x2aced130)
|   mManagedDialogs = null
|   mMenuInflater = null
|   mParent = null
|   mReferrer = java.lang.String@718234256 (0x2acf6290)
|   mResultCode = 0
|   mResultData = null
|   mResumed = false
|   mSearchEvent = null
|   mSearchManager = null
|   mStartedActivity = false
|   mStopped = true
|   mTaskDescription = android.app.ActivityManager$TaskDescription@718209344 (0x2acf0140)
|   mTemporaryPause = false
|   mTitle = java.lang.String@717968576 (0x2acb54c0)
|   mTitleColor = 0
|   mTitleReady = true
|   mToken = android.os.BinderProxy@718245984 (0x2acf9060)
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread@1944190976 (0x73e20000)
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.PhoneWindow@718009248 (0x2acbf3a0)
|   mWindowAdded = true
|   mWindowManager = android.view.WindowManagerImpl@718197352 (0x2aced268)
|   mInflater = com.android.internal.policy.PhoneLayoutInflater@718201184 (0x2acee160)
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources@718217552 (0x2acf2150)
|   mTheme = android.content.res.Resources$Theme@718193216 (0x2acec240)
|   mThemeResource = 2131492869
|   mBase = android.app.ContextImpl@718278784 (0x2ad01080)
|   shadow$_klass_ = testvolley.dn.java.testvolley.ApiActivity
|   shadow$_monitor_ = -1954971875
* Excluded Refs:
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.textservice.SpellCheckerSession$1.this$0
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by jpd236** [comment] 2017-11-01 19:37
Thank you for all of the detailed information and especially the sample app! I can at least reproduce the leak now, although I'm not yet sure why it's happening. I think this came up previously in https://github.com/google/volley/issues/19 and was closed as we didn't have needed details.

While it was definitely necessary to have Requests clear their listeners on cancel, because Volley internals are still holding onto the Request object while the request is being dispatched, it should _not_ be necessary for Requests to have to do anything after the request is finished. The bug would be that something in Volley is holding a reference to a finished Request as it shouldn't be doing so.

That being said, I can't make sense of why CacheDispatcher/NetworkDispatcher are seen as holding references to the finished request. In the heap dumps / LeakCanary output it just shows up as "Java local" without a variable name. But I don't see what local variable is holding onto the request.

**Comment by joebowbeer** [comment] 2017-11-02 02:55
Either (1) there is a bug in `RequestQueue.cancelAll()` or (2) LeakCanary is fooled by a delayed call to `Activity.onDestroy()`.

Assuming RequestQueue.cancelAll is correct, one way to avoid this false alarm would be to move cancelAll() from the test Activity's onDestroy method to either onStop or onPause, perhaps preceded by a call to isFinishing().

I also notice that the anonymous listeners class holds a strong reference to its Activity. For robustness, I recommend using a static nested listener with a weak reference to the Activity. This might be enough to assuage LeakCanary.

Looking at the instances reported by LeakCanary, I think the following two objects are, respectively, the current instance of ApiActivity and its userApiListeners instance:

```
ApiActivity@717956704
  userApiListeners -> ApiActivity$1@717868097

ApiActivity$1@717868097
  this$0 -> ApiActivity@717956704
```

The interesting instances where the leak occurs are as follows:

```
CacheDispatcher -> ApiRequest@717876225

ApiRequest@717876225
  mListener -> ApiActivity$1@718193072
  mErrorListener -> ApiActivity$1@718193072

ApiActivity$1@718193072
  this$0 -> ApiActivity@717987841

ApiActivity@717987841 [LEAKED]
  userApiListeners -> ApiActivity$1@718193072
```

Observations:

1. The leaked Activity is finished (`mFinished = true`). This means that finish() has been called, but onDestroy may not have been called. In fact, I believe onDestroy may not be called until after the new Activity's onCreate has been called. The leaked Activity does not cancel its requests until onDestroy is called.

2. The ApiRequest instance has not been canceled (`mCanceled = false`).

**Comment by Dayanand515** [comment] 2017-11-02 07:52
I don't see any indication that the ApiRequest instance is finished.
>> This can be conformed from logcat logs , use filter 'logs'


Regarding the reported leak of ApiActivity, either:

There is a bug in RequestQueue.cancelAll() -or-
>> Since request is finised and removed from com.android.volley.RequestQueue#mCurrentRequests hence cancel on request is not called.


LeakCanary is fooled by a delayed call to Activity.onDestroy()
>> As per logs onDestroy is getting called within short duration.

Even then cache dispatcher is referencing request listner.

**Comment by joebowbeer** [comment] 2017-11-02 14:55
@Dayanand515 thanks for correcting my analysis.

**Comment by Dayanand515** [comment] 2017-11-02 18:47
@joebowbeer what do you recommend to fix this leak.
I believe we can add onStop method and clears listener inside onStop as handled at https://github.com/mcxiaoke/android-volley/commit/c111d14699a2235ea5d3af51b40bcf67ba310bf8

**Comment by joebowbeer** [comment] 2017-11-03 14:16
@Dayanand515 The response for the ApiRequest that is retained by CacheDispatcher has not yet been delivered:

```
mResponseDelivered = false
```

Are you sure this request is finished?

**Comment by jpd236** [comment] 2017-11-03 19:49
@joebowbeer markDelivered looks like its only called for successful responses. This sample app gets an error response by intentionally hitting a bogus URL.

@Dayanand515 we need to figure out why something is holding a reference to the Request inside Volley. Requiring every Request subclass to clear the listener when a request is finished is not ideal at all (we had to do it to cover the cancel case, but it shouldn't be necessary here), and still means we're leaking the Request object even if the listeners aren't leaked. The CL you linked covers the error listener, but presumably in most cases the response listener is also affected and that is out of the scope of Request itself.

Need to look at this more, likely by trying to strip down the code to the minimum possible reproduceable case. It's possible this is a Volley bug... but it's also possible this is something wrong at a lower level (which might or might not be something we can work around).

**Comment by jpd236** [comment] 2017-11-04 00:07
What I'm observing is very strange. I can not reproduce the issue if I comment out the call to mCurrentRequests.remove(request) in RequestQueue#finish. I can't possibly see how that would be causing a leak as it's supposed to be _removing_ a reference to the request. But as far as I can tell, it's 100% reliable.

**Comment by joebowbeer** [comment] 2017-11-04 01:08
This anonymous inner Runnable in CacheDispatcher is a little fishy:

```
    mDelivery.postResponse(request, response, new Runnable() {
        @Override
        public void run() {
            try {
                mNetworkQueue.put(request);
            } catch (InterruptedException e) {
                // Restore the interrupted status
                Thread.currentThread().interrupt();
            }
        }
    });
```

It references the final `request` local variable inside the thread's run() method. A static nested class with explicit request and networkQueue fields would make this more explicit.

**Comment by jpd236** [comment] 2017-11-06 18:44
- I don't follow why lock acquisition would be related here, but anyway I can remove the lock but keep the remove call and the leak still reproduces.

- The runnable pointed out only runs if something is being pulled from the cache, which is not the case here; indeed you can replace the entire loop of CacheDispatcher with a hard-coded call to post the error directly to the response delivery and still reproduce the issue.

I think the way forward here will be to try to distill this into a minimal repro case.

**Comment by jpd236** [comment] 2017-11-08 02:14
OK, I have a fairly minimal repro case which is attached here. This isolates this from all of Volley's internals and any actual network activity / switches between activities. Still investigating.
[TestVolley.zip](https://github.com/google/volley/files/1452366/TestVolley.zip)

**Comment by jpd236** [comment] 2017-11-08 18:47
OK. This does indeed appear to have been the same as #19. Contrary to the linked blog post there, this issue was not actually fully resolved and has resurfaced in recent versions of the platform, even with ART.

The workaround from the blog post of posting an empty item to the queue every second is not ideal as that would churn threads that should otherwise be idle. Instead we can try the tack of extracting the body  of the loop to a helper method. It's not a 100% guarantee since Proguard could theoretically optimize it, but in practice it's probably good enough and is likely the best we can do.

Here's an example of that workaround in practice: https://android.googlesource.com/platform/frameworks/support/+/cd07a0cfd9c9501a03c574d2d48df51c82b73e33

PR coming shortly.

**Comment by jpd236** [comment] 2017-11-08 18:47
OK. This does indeed appear to have been the same as #19. Contrary to the linked blog post there, this issue was not actually fully resolved and has resurfaced in recent versions of the platform, even with ART.

The workaround from the blog post of posting an empty item to the queue every second is not ideal as that would churn threads that should otherwise be idle. Instead we can try the tack of extracting the body  of the loop to a helper method. It's not a 100% guarantee since Proguard could theoretically optimize it, but in practice it's probably good enough and is likely the best we can do.

Here's an example of that workaround in practice: https://android.googlesource.com/platform/frameworks/support/+/cd07a0cfd9c9501a03c574d2d48df51c82b73e33

PR coming shortly.

**Closed** 2017-11-10 22:35 UTC

**Comment by jpd236** [comment] 2017-11-10 22:46
@Dayanand515 - could you try compiling against the latest 1.1.0-SNAPSHOT from the https://oss.jfrog.org/artifactory/oss-snapshot-local/ repository to verify that it resolves the issue in your full app?

**Comment by Dayanand515** [comment] 2017-11-15 17:29
@jpd236 / @joebowbeer  1.1.0-SNAPSHOT from oss-snapshot-local works as expected, doesn't reproduce any memory leaks.
Thanks.

**Comment by mitpjones** [comment] 2017-11-20 07:30
I have also tested and seems to be fixed.

Thanks
