### ISSUE TITLE
Volley not working sometimes

### ISSUE THREAD

**Issue by rickyManalo** [google/volley#264] opened 2019-03-22 03:58 UTC
I have this code for getting a list of video from a local API.

```
public void getVideoAds(String serverURL){
	String url = "http://"+serverURL+"/video/";

	StringRequest stringRequest = new StringRequest(url, new Response.Listener<String>() {
		@Override
		public void onResponse(String response) {
			try {
				JSONObject jsonObj = new JSONObject(response);
				JSONObject defaultObj = jsonObj.getJSONObject("default");
				JSONArray videoObj = jsonObj.getJSONArray("videos");

				defaultUrl = defaultObj.getString("url");

				for (int i = 0; i < videoObj.length(); i++){
					JSONObject video = videoObj.getJSONObject(i);

					VideoAd v = new VideoAd();
					v.setName(getVideoNameFromLink(video.getString("url")));
					v.setUrl(video.getString("url"));
					v.setVideoId(video.getInt("id"));
					v.setVersion(video.getInt("version"));
					v.setLocalPath("");

					vidArrLst.add(v);
				}

				playLoopVideo();
			} catch (Exception e) {
				Log.d(TAG, "getVidAds res err: " + e.getMessage());
			}

		}
	}, new Response.ErrorListener() {
		@Override
		public void onErrorResponse(VolleyError error) {
			Log.d(TAG, "getVidAds err: " + error.getMessage());
		}
	});

	queue.add(stringRequest);
}
```

Sometimes it works. Sometimes it doesn't. And when it doesn't work, I'm not getting any error even if I'm using Exception on my catch(). If I do a Clean Project -> Rebuild Project -> Make Project, it works again. But after a few builds, mostly after 1 build, it stops working again. 

I'm using the latest version of  Volley. `implementation 'com.android.volley:volley:1.1.1'`
I'm also initializing RequestQueue in my onCreate using this as my context.
If you need more info, please refer to this [SO question](https://stackoverflow.com/questions/55292686/android-volley-stringrequest-not-working-sometimes).

UPDATE:

Hi, I've added more information on my SO question. To summarize it, it seems that if one of the `StringRequest` added into a `RequestQueue` receives an empty response, everything stops working. And it even affects `ExoPlayer`.

**Comment by jpd236** [comment] 2019-03-22 17:35
There's not really enough information here for us to be able to dig into this too much. It sounds like the nature of your issue is a flaky one, so we'd probably need to be able to reproduce it locally, but this snippet wouldn't be enough to do so. Is it possible for you to isolate the problem in a small sample app?

The only other thought I have is that there's a known issue in the platform with some media player APIs and HttpUrlConnection causing requests to be corrupted (https://issuetracker.google.com/113756447). You might try using a different HttpStack implementation to see if that resolves the problem. Otherwise, there's no situation I'm aware of where you successfully call RequestQueue#add on a started RequestQueue where it just never invokes either the response listener or the error listener.

**Comment by uhager** [comment] 2019-03-22 19:13
>   Otherwise, there's no situation I'm aware of where you successfully call RequestQueue#add on a started RequestQueue where it just never invokes either the response listener or the error listener.

Maybe not relevant here, but just for completeness (and because we once came across the second one and I spent some time tracking it down):
* it could be that somewhere else in the app someone calls RequestQueue#cancelAll
* a bit trickier to find: if something else blocks the main thread, the runnable that ExecutorDelivery puts on the main thread won't run, so it will look like Volley swallowed the request.

**Comment by rickyManalo** [comment] 2019-03-23 01:06
Yesterday, I was able to make it work. On my app I got 2 methods that call 2 different API from our server. The 1st one is the one above which is getVideoAds() and the other one is getMessageAds(). Both methods are inside another method so I can call them simultaneously. Currently, getMessageAds() receives an empty response. Just for the sake of experimenting, I commented out getMessageAds() and everything worked fine again. Even `ExoPlayer` don't get stuck on buffering again. I'll give a sample app ASAP.

**Comment by rickyManalo** [comment] 2019-03-27 04:23
Sorry for the very late reply. This is my [sample app](https://drive.google.com/file/d/1kHv9Xj1C7hav50Lqe9N5q3mzBv5phGp3/view?usp=sharing). I'm not a back-end developer but I added a sample json result on a text file so you guys can see what the response should look like. I think you can just make a page that display those things.

**Comment by jpd236** [comment] 2019-03-27 22:33
I tested your sample code on a Nexus 6 running Android N (MR2), with the following tweaks:

1. Your get*Ads methods never actually queued the requests, so I added queue.add(stringRequest) to the end of both of them.
2. Rather than set up an HTTP server, I provided a fake HTTP stack that would wait a second and then reply with the appropriate response:

```java
    queue = Volley.newRequestQueue(this, new BaseHttpStack() {
            @Override
            public HttpResponse executeRequest(
                    Request<?> request,
                    Map<String, String> additionalHeaders) {
                SystemClock.sleep(1000L);
                switch (request.getUrl()) {
                    case "http://"+SERVER_IP_ADDRESS+"/apin":
                        return new HttpResponse(200, new ArrayList<Header>(),
                            videoAds.length(), new ByteArrayInputStream(videoAds.getBytes()));
                    case "http://"+SERVER_IP_ADDRESS+"/apim":
                        return new HttpResponse(200, new ArrayList<Header>(),
                            messageAds.length(), new ByteArrayInputStream(messageAds.getBytes()));
                    default:
                        return new HttpResponse(400, new ArrayList<Header>());
                }
            }
        });
```

I hit the button a few times and always saw both responses logged to logcat.

So nothing seems to be working unexpectedly here. Do you have more details about how to reproduce the problem you're seeing?

**Comment by rickyManalo** [comment] 2019-03-28 01:23
Oops, sorry. I think I did forgot to make a queue.add(). Did you make 1 of the response to be empty? Because that's the only way I was able to make it not work. The tablet I was using is running Lollipop. 

This are the info of my Android Studio:

Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

Hope that helps.

**Comment by jpd236** [comment] 2019-03-28 18:19
I set messageAds (just a String) in the above sample code to the empty string and the Response.Listener is still called for both functions. Perhaps you could try integrating the above change to make a local server into your sample code and seeing if you can reproduce, because if this is dependent on a server then it will be harder for us to replicate the same environment. You've said your server is returning an empty response but I don't really know what that means in practice.

**Comment by rickyManalo** [comment] 2019-03-29 06:26
I tried to fix my copy and include your HTTP stack code and it worked on my sample project. I was able to get the responses on my real project as well but it doesn't execute the rest of the code inside the onResponse listener. Inside the getMessageAds(), I use the response to make a marquee then I use the responses on getVideoAds as an item for a videoAd ArrayList. Both request just display the responses which is placed above a try-catch and that try catch doesn't get executed and never return an error. I think I misunderstood an empty string response to a real empty response, sorry.

**Comment by jpd236** [comment] 2019-03-29 17:36
If onResponse is consistently being invoked, but something is not working as expected inside your onResponse, then I have to imagine that's something specific to your app and not Volley.

I'm closing this out as at this point I'm not seeing anything that could be going wrong on Volley's end. However, I'm happy to continue to look if you can provide more info on what you think is not happening as expected on the Volley side.

**Closed by jpd236** 2019-03-29 17:36 UTC

**Comment by rickyManalo** [comment] 2019-03-30 01:01
Sure, I was about to close this as well because it seems that it was my own error. Thank you.
