### ISSUE TITLE
DiskBasedCache breaks if the user clears app cache while the app is still running.

### ISSUE THREAD

**Issue by ajnas** [google/volley#296] opened 2019-10-01 17:49 UTC
When using the default DiskBasedCache, if the app cache gets cleared, the default directory for the volley caches also gets deleted. In this instance, future cache writes happening in the RequestQueue fails as the root directory for saving the cache files does not exist anymore.

Creating the root folder for volley caches (ie, 'volley' folder in cache directory) is done during the start() function of the CacheDispatcher which is triggered during the start of the RequestQueue.

This causes the unexpected cache misses If the app keeps the RequestQueue as a singleton instance in the memory.

**Comment by jpd236** [comment] 2019-10-01 18:31
This was reported internally as well a while back, so I can confirm it's a valid issue. We'll look into a fix.

**Comment by ajnas** [comment] 2019-10-01 19:14
@jpd236 After spending some time debugging this issue, I see that put method in [DiskBasedCache](https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/DiskBasedCache.java) always just assume the mRootDirectory exists before it tries to create new cache entry files inside it. How about doing mkdirs() before attempting to write the file inside put? 

What are your thoughts?

**Comment by jpd236** [comment] 2019-10-02 19:50
Should be fixed by https://github.com/google/volley/pull/297. It's not quite as trivial as mkdirs() before a write because the in-memory state (e.g. the map of cache entry headers) becomes invalid as well.

**Closed** 2019-10-03 00:49 UTC
