### ISSUE TITLE
Fatal Exception: No NameTypeIndex match for SHORT_STANDARD

### ISSUE THREAD

**Issue by TuanNA-MTITech** [google/volley#177] opened 2018-05-04 01:59 UTC
I could not reproduce, but I usually got crash message from Fabric Crashlytics Report.

Device:
* Nexus 5X and Nexus 6P. OS version 8.1.0

`Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_STANDARD
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724)
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790)
       at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183)
       at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261)
       at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1296)
       at java.text.SimpleDateFormat.format(SimpleDateFormat.java:1004)
       at java.text.SimpleDateFormat.format(SimpleDateFormat.java:974)
       at java.text.DateFormat.format(DateFormat.java:341)
       at com.android.volley.toolbox.HttpHeaderParser.formatEpochAsRfc1123(SourceFile:152)
       at com.android.volley.toolbox.BasicNetwork.getCacheHeaders(SourceFile:256)
       at com.android.volley.toolbox.BasicNetwork.performRequest(SourceFile:130)
       at com.android.volley.NetworkDispatcher.processRequest(SourceFile:120)
       at com.android.volley.NetworkDispatcher.run(SourceFile:87)`

pls help do investigation on that crash.

**Comment by jpd236** [comment] 2018-05-04 18:51
My theory here would be corruption of the filesystem. If so there's not a ton Volley can do about this. All we're doing is calling SimpleDateFormat with a valid date string and date and that should work, and putting a try-catch around this doesn't seem right for a broken device (as opposed to a broken family of devices, and this is definitely not generally broken on all 5X/6Ps).

Does Crashlytics give you the number of impacted devices?

**Comment by TuanNA-MTITech** [comment] 2018-05-05 03:56
There are 3 devices. 
I could not reproduce that bug. It's sometime happens or always (not sure) on those devices. All of them are 8.1.0

![screen shot 2018-05-05 at 10 48 17 am](https://user-images.githubusercontent.com/38967069/39659420-ec0e6212-5051-11e8-822a-1fb01390606b.png)

Could you add try catch like this:

```
private Map<String, String> getCacheHeaders(Cache.Entry entry) {
        // If there's no cache entry, we're done.
        if (entry == null) {
            return Collections.emptyMap();
        }

        Map<String, String> headers = new HashMap<>();

        if (entry.etag != null) {
            headers.put("If-None-Match", entry.etag);
        }

        if (entry.lastModified > 0) {
            try {
                    headers.put("If-Modified-Since",
                              HttpHeaderParser.formatEpochAsRfc1123(entry.lastModified));
             } catch(Exception e) {}
        }
        return headers;
    }

```

**Comment by jpd236** [comment] 2018-05-07 17:48
I'll consider it, but am leaning against it. Devices in this state must be pretty broken for other reasons so trying to catch this one particular crash is unlikely to resolve any issue. Note that there are other calls which use this SimpleDateFormat (e.g. to parse timestamps out of the response) that are just not being reached here, and also it's unclear what the right behavior would be. We could just gracefully fail the requests, but is that really that much better?

**Comment by jpd236** [comment] 2018-05-07 17:49
(Again - if this were an issue impacting a full device family and there was a known workaround, I think it would be reasonable for us to apply it. But for sporadic failures on a device family that otherwise is known to work, and for which we don't have any way to reproduce or test a workaround, or any idea what such a workaround would look like, I'm hesitant to take a fix. These devices are probably broken).

**Comment by jpd236** [comment] 2018-05-30 22:02
I raised this issue with some Android folks who maintain the underlying library. They'll look into the pattern to see if there's something wrong from the platform side that can be addressed. However, they agree that it's not reasonable/feasible for the library to try and guard against this exception as it's infeasible to try and catch absolutely everything that might format a date or use ICU in general.

Given this, I'm going to close this as infeasible for now. We'll keep an eye on frequency of reports, and if this comes up in other contexts or with more frequency, we can look further.

**Closed by jpd236** 2018-05-30 22:02 UTC

**Comment by abeatte** [comment] 2018-06-20 15:33
This type of error is something I am seeing more as well. It seems to be specific to Android 8.

**Comment by TuanNA-MTITech** [comment] 2018-06-28 02:07
I think it may not a device's problem.

**Comment by mtrakal** [comment] 2018-08-14 08:06
It's not a device specific problem, but the API level...
We updated to target SDK API level 26 and it started crashing on Android 8 immediately.

http://crashes.to/s/bdf71a655d4

**Comment by jsa-nic** [comment] 2018-09-06 01:56
Indeed it appears to be a platform issue, see this Facebook SDK work-around: https://stackoverflow.com/a/52035884/2775083

Also see this issue which appears to track the problem: https://issuetracker.google.com/issues/110848122

**Comment by Lingviston** [comment] 2021-05-17 20:22
How the absence of "If-Modified-Since" header would influence the request processing if I implemented custom Network with the fix from here:
`private Map<String, String> getCacheHeaders(Cache.Entry entry) {
        // If there's no cache entry, we're done.
        if (entry == null) {
            return Collections.emptyMap();
        }

        Map<String, String> headers = new HashMap<>();

        if (entry.etag != null) {
            headers.put("If-None-Match", entry.etag);
        }

        if (entry.lastModified > 0) {
            try {
                    headers.put("If-Modified-Since",
                              HttpHeaderParser.formatEpochAsRfc1123(entry.lastModified));
             } catch(Exception e) {}
        }
        return headers;
    }
`
