### ISSUE TITLE
Fix nullability issues in Kotlin sample code

### ISSUE THREAD

**Issue by zym2013** [google/volley#445] opened 2022-10-28 10:26 UTC
### next is my code

`val url2 = "http://ngx.cn/api/v1/cloud/auth/captcha/file/${captchaId}.png"`
`captchaImage.setDefaultImageResId(R.color.white)`
`captchaImage.setErrorImageResId(R.color.black)`
`val imageLoader = SingletonVolley.getInstance(requireActivity()).imageLoader`
`captchaImage.setImageUrl(url2, imageLoader)`

### ERROR

`java.lang.NullPointerException: cache.get(url) must not be null
 at com.example.ngxmobileclient.SingletonVolley$imageLoader$2$1.getBitmap(SingletonVolley.kt:28)
 at com.android.volley.toolbox.ImageLoader.get(ImageLoader.java:227)
 at com.android.volley.toolbox.NetworkImageView.loadImageIfNecessary(NetworkImageView.java:245)
 at com.android.volley.toolbox.NetworkImageView.setImageUrl(NetworkImageView.java:109)
 at com.example.ngxmobileclient.ui.login.LoginFragment.getCaptcha$lambda-8(LoginFragment.kt:156)
 at com.example.ngxmobileclient.ui.login.LoginFragment.$r8$lambda$n1UUm1SdW0SH2_V01mipVoJ8p98(Unknown Source:0)
 at com.example.ngxmobileclient.ui.login.LoginFragment$$ExternalSyntheticLambda5.onResponse(Unknown Source:6)
 at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:100)
 at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:207)
 at android.app.ActivityThread.main(ActivityThread.java:6878)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)`

**Comment by jpd236** [comment] 2022-10-28 17:09
The crash is in com.example.ngxmobile.SingletonVolley which is a class in your app, not Volley. Seems like you're assuming that an entry will be in the Cache, which is not guaranteed.

Not much more we can do to help from the Volley side; since the issue doesn't appear to be in Volley itself, I'd probably recommend a more general purpose help medium like StackOverflow or our user group at volley-users@googlegroups.com, since this is an issue tracker for issues with Volley itself. That said, if you think there is an issue with Volley, please provide the full sample (including the class which is crashing) and explain where you think the issue is.

**Comment by zym2013** [comment] 2022-10-28 19:10
Thank you for your help, because I wrote this paragraph according to the example code of the singleton. I'm very sorry for the trouble.



发自我的小米手机在 Jeff Davidson ***@***.***>，2022年10月29日 01:09写道：
The crash is in com.example.ngxmobile.SingletonVolley which is a class in your app, not Volley. Seems like you're assuming that an entry will be in the Cache, which is not guaranteed.
Not much more we can do to help from the Volley side; since the issue doesn't appear to be in Volley itself, I'd probably recommend a more general purpose help medium like StackOverflow or our user group at ***@***.***, since this is an issue tracker for issues with Volley itself. That said, if you think there is an issue with Volley, please provide the full sample (including the class which is crashing) and explain where you think the issue is.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/google/volley/issues/445#issuecomment-1295246059",
"url": "https://github.com/google/volley/issues/445#issuecomment-1295246059",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jpd236** [comment] 2022-11-07 17:58
The above change to the sample code should hopefully resolve the issue. Let us know if not.

**Closed by jpd236** 2022-11-07 17:58 UTC
