### ISSUE TITLE
Send Header and Params

### ISSUE THREAD

**Issue by brandonsousa** [google/volley#338] opened 2020-05-14 21:15 UTC
` 
public void newIndication(final Indication indication) {

        stringRequest = new StringRequest(

                Request.Method.POST,
                Api.INDICATION,
                new Response.Listener<String>() {

                    @Override
                    public void onResponse(String response) {

                        ToastMessage.showMessage(context, response);
                        try {
                            JSONObject jsonObject = new JSONObject(response);
                            if (jsonObject.getBoolean("indication")) {
                                ToastMessage.showMessage(context, jsonObject.getString("messagee"));
                            } else {
                                ToastMessage.showMessage(context, jsonObject.getString("messagee"));
                            }
                        } catch (JSONException e) {
                            ToastMessage.showMessage(context, "JSONException -> \n " + e.getMessage());
                        }
                    }

                }, new Response.ErrorListener() {

            @Override
            public void onErrorResponse(VolleyError error) {
                ToastMessage.showMessage(context, "VolleyError -> \n " + error.getMessage());
            }

        }) {

            @Override
            protected Map<String, String> getParams() throws AuthFailureError {
                HashMap<String, String> param = new HashMap<>();
                param.put(IndicationDM.NAME, indication.getName());
                param.put(IndicationDM.CITY, indication.getCity());
                param.put(IndicationDM.UF, indication.getUf());
                param.put(IndicationDM.PHONE, indication.getPhone());
                return param;
            }

            @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                HashMap<String, String> header = new HashMap<>();
                header.put(TokenDM.CONTENT, TokenDM.TYPE);
                header.put(TokenDM.AUTHORIZATION, TokenDM.BEARER + token.getToken());
                return header;
            }
        };
        requestQueue.add(stringRequest);
    }`

I'm trying to register by passing the token through the header and sending the data through the params but the data doesn't arrive, but if I remove the header it works normal, someone could give a light

**Comment by jpd236** [comment] 2020-05-14 21:50
Assuming you are using the default HurlStack, all headers do is result in a call to HttpUrlConnection#setRequestProperty:

https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/HurlStack.java#L93

There's no reason that should impact the request body. Sounds like either something on the server side or something else going wrong with your app, but I don't see anything in your code that looks wrong.

Maybe try making the request directly with HttpUrlConnection since it's a simple string request, and if that works, compare with that HurlStack is generating until you find the difference.

**Comment by brandonsousa** [comment] 2020-05-15 20:52
this is all my request, with RequestQueue and StringRequest, I tested my api with the insomnia passing the token and the params, it works normal, if I remove the token my request works, but when I pass the header and the params, the header goes and the params reaches zero there

**Comment by jpd236** [comment] 2020-05-15 22:37
What about with HttpUrlConnection? Volley is just wrapping that under the covers.

**Comment by pritamfusion2021** [comment] 2021-11-29 07:39
Same Problem😒😥😪😭

**Comment by pritamfusion2021** [comment] 2021-11-29 07:42
Please Give Me a Solutions...😒😥😪😭

**Comment by jpd236** [comment] 2021-11-29 17:31
Since the original reporter hasn't followed up here, I'm closing this out. Please do comment if you're able to reproduce a problem with Volley but not HttpUrlConnection.

@pritamfusion2021 see https://github.com/google/volley/issues/338#issuecomment-628905035. If you think you're experiencing a problem, please try to reproduce with HttpUrlConnection directly to determine whether the issue is in Volley or somewhere else.

**Closed by jpd236** 2021-11-29 17:31 UTC
