### ISSUE TITLE
ConcurrentModificationException on cancel

### ISSUE THREAD

**Issue by yaalaa** [google/volley#455] opened 2023-07-17 14:42 UTC
Prerequisites -
- Android SDK: API34 (API33)
- Runtime: API33, API30
- com.android.volley:volley:1.2.1
 
Steps -
- start loading several images
- cancel all

Expected -
- loaders are canceled

Actual -
- app crashes with exception `ConcurrentModificationException`
- stack looks like
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
	at com.android.volley.toolbox.ImageLoader$4.run(ImageLoader.java:495)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

Any help?

**Comment by jpd236** [comment] 2023-07-17 17:02
This looks like a duplicate of #205. If you could provide sample code there that at least somewhat consistently reproduces the issue, that would be quite helpful.

**Closed by jpd236** 2023-07-17 17:02 UTC
