### ISSUE TITLE
API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.

### ISSUE THREAD

**Issue by misaghE** [google/volley#290] opened 2019-08-31 06:52 UTC
Using the last release of library, I face this line in build output after successful build:

```
INFO: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: volley
```

The project compiles and runs correctly.

**Comment by jpd236** [comment] 2019-09-03 17:12
We have some cleanup to do here to bring the project back up to sync with latest best practices, but this isn't essential since everything is still building fine. This is somewhat blocked because newer build tools enforce that AndroidManifest.xml not include the minSdkVersion, but we copy Volley's source into Google's internal source tree / build system, which requires the manifest include the minSdkVersion.

None of this should impact using Volley binaries from Bintray.

**Comment by jpd236** [comment] 2020-06-04 18:28
We've upgraded to newer versions of the gradle plugin and other dependencies since this was filed and made some tweaks to our gradle scripts. I'm not sure if this warning was fixed as we weren't able to reproduce it recently though. Closing this out, but please feel free to reopen with more detailed reproduction steps (e.g. the build command) if you're still seeing this.

**Closed by jpd236** 2020-06-04 18:28 UTC
