### ISSUE TITLE
Can't read "contentType" from cache

### ISSUE THREAD

**Issue by dingbuoyi** [google/volley#76] opened 2017-08-24 03:19 UTC
I have met a issue , when I try to get the "contentType" from cache, it always return null.
Then I checked the source code of "DiskBasedCache" and "BasicNetwork".

It turns out that in "DiskBasedCache" , the volley use "HaspMap" to save the http headers and in 
"BasicNetwork" it uses "new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER)" which
is not case sensitive.

So if the server's response header, uses "content-type" rather than "Content-Type", it can work properly with a response from network but can't get contentType from the cache.

And because of this issue , you can't parse the charset from cache  , and it will use the default charset which is "ISO_8859_1" , and if it doesn't match the actually charset which you should get from "content-type" , then you can't get the right response content with the right charset from cache.

**Comment by joebowbeer** [comment] 2017-08-24 05:15
I think I see what you're referring to.

HttpHeaderParser is *expecting* to see a normalized header map: [HttpHeaderParser#L145](https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/HttpHeaderParser.java#L145)

and BasicNetwork converts its headers to a string-insensitive map before they are cached:  [BasicNetwork#L101](https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/BasicNetwork.java#L101)

BUT if a cached entry is returned, its header map is parsed, and its map will not perform case-insensitive header comparisons: [CacheDispatcher#L119](https://github.com/google/volley/blob/master/src/main/java/com/android/volley/CacheDispatcher.java#L119)

It should be easy to write a failing unit test.

**Comment by dingbuoyi** [comment] 2017-08-24 06:51
@joebowbeer 

Thank you for reply.  You completely get my point.
Should I write the unit test or you will?

**Comment by joebowbeer** [comment] 2017-08-24 20:32
@dingbuoyi feel free to write the unit test and/or PR

Looking at this a little closer, I think the fix needs to be at the sites where the NetworkResponse is created. The Cache interface doesn't spec this contract currently.

In particular, CacheDispatcher should convert the headers before passing them to the NetworkResponse constructor: [CacheDispatcher#L118](https://github.com/google/volley/blob/master/src/main/java/com/android/volley/CacheDispatcher.java#L118)

```
    Map<String, String> responseHeaders =
            new TreeMap<>(String.CASE_INSENSITIVE_ORDER).putAll(entry.responseHeaders);
    Response<?> response = request.parseNetworkResponse(
            new NetworkResponse(entry.data, responseHeaders));
```

The 304 handling in BasicNetwork is also questionable: [BasicNetwork#L116](https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/BasicNetwork.java#L116)

One fix is to add the cache's headers to the responseHeaders TreeMap, instead of the other way around:

```
    responseHeaders.putAll(entry.responseHeaders); // add to TreeMap
    return new NetworkResponse(HttpStatus.SC_NOT_MODIFIED, entry.data,
            responseHeaders, true, SystemClock.elapsedRealtime() - requestStart);
```

In addition, this implicit contract should be documented somewhere, but where?

**Comment by dingbuoyi** [comment] 2017-08-29 06:23
@joebowbeer 

I have tried your code, of course it solved the problem .But as you can see , if you pass the responseHeaders instead of entry.responseHeaders , it kind of inconsistence.

If a NetworkResponse comes from a cache, it should use "entry.responseHeaders" and if it comes from network , it should use “responseHeaders”.

As a matter of fact , I think there is a easy way to solve this : DiskBasedCache#L565
It should use a case sensitive map not a hash map.

```
    static Map<String, String> readStringStringMap(InputStream is) throws IOException {
        int size = readInt(is);
        Map<String, String> result = (size == 0)
                ? Collections.<String, String>emptyMap()
                : new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
        for (int i = 0; i < size; i++) {
            String key = readString(is).intern();
            String value = readString(is).intern();
            result.put(key, value);
        }
        return result;
    }
```
Later I will make a PR for fixing this issue.

**Comment by joebowbeer** [comment] 2017-08-29 06:35
@dingbuoyi The problem I see with trying to push this into DiskBasedCache is that DBC is only one implementation of Cache. All the other implementations would also need to change. In effect, you would be changing the Cache interface to require the use a case-insensitive map.

**Comment by dingbuoyi** [comment] 2017-08-29 06:41
@joebowbeer 

You are right, I did not think of that.

**Comment by jpd236** [comment] 2017-08-29 19:46
Instead of requiring all of NetworkResponse's callers to pass in a sorted map, why not have NetworkResponse construct the appropriate map itself based on the input map?

Then you only need to have one location in the codebase constructing the TreeMap; everything else can just pass in any kind of map as is convenient. And the question above re: documentation can be resolved by updating the NetworkResponse#headers Javadoc to note that the map is case-insensitive.

**Comment by dingbuoyi** [comment] 2017-08-30 02:22
@jpd236 

Yes , of course , I also have considered your solution. My only concern is that I can't find a way to 
check the input map is already a case-insensitive map or not.That means I have to convert every
input map to a case-insensitive map no matter it is appropriate or not.

**Comment by cfcodefans** [comment] 2017-08-30 03:37
I think the issue is related to the implementation of Cache.
Map of headers works as container of data but also has different behaviors in different implement,
as Map of headers got serialized to data in disk, it loses its type information.
Therefore as the headers is deserialized from disk, from the lib's point of view, it can try its best to provide a Hashmap which could lead to behavior different than the original Map.
How about allowing developer to pass a map into the deserialization method so the map's behavior could keep consistent?

**Comment by joebowbeer** [comment] 2017-08-30 04:08
I just noticed a report related to this on SO from 2013, with many responses and some suggested workarounds, one as recent as 2017:

[Why does volley's response string use an encoding different from that in the response headers?
](https://stackoverflow.com/q/19267616/901597)

I haven't studied these carefully to see if any of the fixes suggested here will break prior workarounds.

**Comment by joebowbeer** [comment] 2017-08-30 04:36
I'm coming-around to the idea of "fixing" this in ``DiskBasedCache#readStringStringMap``

I think that can be viewed as a backward-compatible enhancement.

A note could be added to the Cache documentation indicating that best practice is to return a case-insensitive map.

Either way, I think the 304 handling ([BasicNetwork#L116](https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/BasicNetwork.java#L116)) needs to be fixed as I indicated previously, right?

**Comment by cfcodefans** [comment] 2017-08-30 05:18
I suggest to add another overload method

```
static Map<String, String> readStringStringMap(InputStream is, Map<String, String> stringMap) throws IOException {
        int size = readInt(is);
        Map<String, String> result = (size == 0)
                ? Collections.<String, String>emptyMap()
                : stringMap; new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
        result = result != null ? result : 
        for (int i = 0; i < size; i++) {
            String key = readString(is).intern();
            String value = readString(is).intern();
            result.put(key, value);
        }
        return result;
    }
```

**Comment by joebowbeer** [comment] 2017-08-30 05:26
@cfcodefans The existing method is package private. What benefit is there in adding a new method?

**Comment by cfcodefans** [comment] 2017-08-30 05:28
@joebowbeer 
Oh, yes, you are right, I overlooked

**Comment by dingbuoyi** [comment] 2017-08-30 07:03
@joebowbeer @jpd236 @cfcodefans 

I think since "DiskBasedCache" has already been part of this library , and it uses "Hashmap" which will certainly caused the issue I have met. So that should be fixed.

And like @joebowbeer said a note added to the Cache documentation will be very helpful to those who want to implement the cache themselves.

**Comment by jpd236** [comment] 2017-08-30 15:02
Sorry, but I'm still in favor of the solution I proposed above :)

"My only concern is that I can't find a way to
check the input map is already a case-insensitive map or not.That means I have to convert every
input map to a case-insensitive map no matter it is appropriate or not."

Within Volley's codebase we can remove all the redundant TreeMap creation so it's no different as long as you're using the stock BasicNetwork / CacheDispatcher. That will resolve the duplicate object creation for nearly all Volley clients, I imagine. An extra object creation for those who have overridden these classes or are otherwise instantiating NetworkResponse objects with case-sensitive maps doesn't feel like a concern vs. the correctness cost of this confusing API contract.

And that will resolve it everywhere as far as I can tell. It will not matter which cache implementation you use. Relying on developers to notice a new best practice in a class that's been around for years doesn't seem likely to catch on, unfortunately. If we find a better representation than TreeMap we can upgrade it internally. It'll resolve the 304 handling as noted above as well (and actually be slightly more efficient AFAICT because we'll defer creation of the TreeMap until we've gathered all the headers in the intermediate map returned from the cache).

**Comment by joebowbeer** [comment] 2017-08-31 06:00
@jpd236 I have no objection to fixing NetworkResponse. It seemed riskier without more analysis, but after looking at it more closely it seems fine.

The fix entails adding an expression to the NetworkResponse constructor, and some refactoring in BasicNetwork?

```
this.headers = new TreeMap<>(String.CASE_INSENSITIVE_ORDER).putAll(headers);
```

What is your take on the code in BasicNetwork ([L116](https://github.com/google/volley/blob/master/src/main/java/com/android/volley/toolbox/BasicNetwork.java#L116)) that mutates the Cache entry's headers?

Should this really be mutating the Cache entry's headers?

**Comment by jpd236** [comment] 2017-08-31 19:35
Yep - that's the change to NetworkResponse, and then in BasicNetwork we remove the convertHeaders method and all calls to it.

Mutating the cache entry's headers does seem unwise. With DiskBasedCache it doesn't seem like too much of an issue because each call to get() will re-read the entry from disk (for better or worse) and put it into a new Entry instance. So, for the scope of an individual request, it's safe AFAICT to mutate that entry because it won't impact the contents of the cache or anyone else's view of the entry except the request being processed. However, it's certainly possible that other cache implementations share instance objects across multiple calls to get() so mutating the entry directly wouldn't be good in that case. We should probably either be copying the CacheEntry map first or else reversing the direction and just skipping put calls for any key that's already in the HTTP response map - bit slower but cuts out the second map allocation, so as long as the header maps are relatively small it's probably fine.

**Comment by dingbuoyi** [comment] 2017-09-01 08:02
@jpd236 

We can't remove the convertHeaders method.

It converts the "Header[]" to "Map<String,String>".

**Comment by jpd236** [comment] 2017-09-01 18:09
Right, but it could use a HashMap instead of a TreeMap when doing so. But we actually probably need to leave it as is and just stop using it because it's protected and thus technically part of the API :(

https://github.com/google/volley/pull/75 also touches a lot of these codepaths... perhaps I should amend it to clean this issue up as well.

**Comment by dingbuoyi** [comment] 2017-09-04 01:50
@jpd236 

sounds great. :)

**Comment by jpd236** [comment] 2017-09-11 19:19
Will actually plan to address as part of other https://github.com/google/volley/issues/21 to keep that open pull request tightly scoped, but keeping this open separately for tracking purposes.

**Comment by jpd236** [comment] 2017-09-14 23:28
https://github.com/google/volley/pull/91 out for review - please feel free to comment if you'd like.

As discussed, this should make the guarantees a bit clearer - NetworkResponse's Map is case-insensitive; no other maps offer guarantees. I think I've kept the data copying / object allocation to the minimum that is feasible while keeping things backwards-compatible, but suggestions welcome. This also cleans up the 304 handling and avoids mutating the value in the cache, although the resulting method is a bit thornier now that we're dealing with lists of headers instead of maps.

**Closed** 2017-09-19 00:21 UTC
