### ISSUE TITLE
Default request header has Accept-Encoding=gzip 

### ISSUE THREAD

**Issue by guillaumebesse** [google/volley#20] opened 2017-04-20 14:09 UTC
But by default, Volley doesn't know how to deal with gzip response.

Something is wrong here... may be me ;-)

**Comment by jpd236** [comment] 2017-04-20 18:53
Duplicate of https://github.com/google/volley/issues/10 - please see my comment there.

**Closed by jpd236** 2017-04-20 18:53 UTC

**Comment by guillaumebesse** [comment] 2017-04-22 19:09
Sorry to insist but I am not sure you understand my question : by default volley doesn't support gzip so why it generates a header with Accept-Encoding=gzip

**Comment by xesam** [comment] 2017-04-23 15:42
@guillaumebesse i think he means "Apache or HttpURLConnection" handle "gzip" header transparently，so it is "Apache or HttpURLConnection" but not "Volley" generates a header with Accept-Encoding=gzip

**Comment by jpd236** [comment] 2017-04-24 04:50
Right. "gzip" is [nowhere](https://github.com/google/volley/search?utf8=%E2%9C%93&q=gzip&type=) in the Volley codebase. If you're seeing it in your request headers than it's either coming from your own code or from the HttpStack implementation that you're using, in which case the HttpStack should be responsible for dealing with the response before it returns the data back to Volley internals.

If you still suspect an issue, please attach sample code, or at least add more details about how to reproduce the issue.
